server:
  port: 8080

management:
  security.enabled: false
  # context-path: /manage
  port: 9001
  # address: 127.0.0.1
  
endpoints:
  shutdown:
    enabled: true

logging:
  level:
    ROOT: WARN
    org.springframework.web: ERROR
    com.rich.dropwizard.metric: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: application-metrics.log


elasticsearch.reporter:
  hosts: 
    - localhost:9200
  index: dropwizard
  indexDateFormat: yyyy.MM.dd
  frequency: 60s

